version: 2
updates:
# The "pip" ecosystem reads the PEP 621 dependencies in pyproject.toml.
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "19:00"
  open-pull-requests-limit: 10
